---
title: "export_dataset"
author: "James Howison"
date: "3/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.world) # loads saved config see quickstart vignette

softcite_ds <- "https://data.world/jameshowison/software-citations/"
```

Data model is:

article has_many selection
selection has_many reference

selection has_many code_application
reference has_many code_application

```{r}


query_string <- "PREFIX bioj: <http://james.howison.name/ontologies/bio-journal-sample#>
PREFIX bioj-cited: <http://james.howison.name/ontologies/bio-journal-sample-citation#>
PREFIX ca: <http://floss.syr.edu/ontologies/2008/4/contentAnalysis.owl#>
PREFIX citec: <http://james.howison.name/ontologies/software-citation-coding#> 
PREFIX dc: <http://dublincore.org/documents/2012/06/14/dcmi-terms/>
PREFIX doap: <http://usefulinc.com/ns/doap#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?article ?coder ?selection ?quote ?page ?mention_type ?certainty ?memo
WHERE {
	?article citec:has_in_text_mention ?selection .
	?selection citec:full_quote ?quote ;
	           citec:on_pdf_page ?page ;
	           ca:isTargetOf [ ca:hasCoder ?coder ;
                             ca:appliesCode [ rdf:type citec:mention_type ;
                                              rdfs:label ?mention_type ;
                                              ca:certainty ?certainty ;
                                              ca:memo ?memo ]
                            ]
}
"
all_mention_query <- data.world::qry_sparql(query_string)

all_mentions <- data.world::query(all_mention_query, softcite_ds) %>% 
  as.tibble %>% 
  filter(str_detect(article, "PMC")) %>% 
  mutate_at(vars(article, selection), funs(str_extract(.,"[#/]([^#/]+)$"))) %>%
  mutate_at(vars(article, selection), funs(str_sub(.,2))) %>% 
  mutate(mention_type = mention_type %>% str_trim() %>% str_to_lower() %>% str_replace_all('"', ''))
  
```

```{r}
all_mentions %>% group_by(mention_type) %>% tally

all_mentions %>% filter(selection %>% str_detect("2001"))
```



Need to get selection-->ref relationship.
```{r}
all_refs_query_string <- "PREFIX bioj: <http://james.howison.name/ontologies/bio-journal-sample#>
PREFIX bioj-cited: <http://james.howison.name/ontologies/bio-journal-sample-citation#>
PREFIX ca: <http://floss.syr.edu/ontologies/2008/4/contentAnalysis.owl#>
PREFIX citec: <http://james.howison.name/ontologies/software-citation-coding#> 
PREFIX dc: <http://dublincore.org/documents/2012/06/14/dcmi-terms/>
PREFIX doap: <http://usefulinc.com/ns/doap#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?selection ?reference ?quote ?page ?reference_type
WHERE {
  ?selection citec:has_reference ?reference .
	?reference citec:full_quote ?quote ;
	           citec:on_pdf_page ?page ;
	           ca:isTargetOf [ ca:hasCoder ?coder ;
                             ca:appliesCode [ rdf:type citec:reference_type ;
                                              rdfs:label ?reference_type ]
                            ]
}
"
all_refs_query <- data.world::qry_sparql(all_refs_query_string)

all_refs <- data.world::query(all_refs_query, softcite_ds) %>% 
  as.tibble %>% 
  filter(str_detect(selection, "PMC")) %>% 
  mutate_at(vars(selection, reference), funs(str_extract(.,"[#/]([^#/]+)$"))) %>%
  mutate_at(vars(selection, reference), funs(str_sub(.,2)))
```



```{r}
all_codes_query_string <- "PREFIX bioj: <http://james.howison.name/ontologies/bio-journal-sample#>
PREFIX bioj-cited: <http://james.howison.name/ontologies/bio-journal-sample-citation#>
PREFIX ca: <http://floss.syr.edu/ontologies/2008/4/contentAnalysis.owl#>
PREFIX citec: <http://james.howison.name/ontologies/software-citation-coding#> 
PREFIX dc: <http://dublincore.org/documents/2012/06/14/dcmi-terms/>
PREFIX doap: <http://usefulinc.com/ns/doap#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?selection ?code ?was_code_present ?code_label
WHERE {
  ?selection rdf:type citec:in_text_mention ;
             ca:isTargetOf [  ca:appliesCode ?ca ] .
  ?ca rdf:type ?code ;
      citec:isPresent ?was_code_present .
  OPTIONAL { ?ca rdfs:label ?code_label }
}
"
all_codes_query <- data.world::qry_sparql(all_codes_query_string)

all_in_text_mention_codes <- data.world::query(all_codes_query, softcite_ds) %>% 
  as.tibble %>% 
  filter(str_detect(selection, "PMC")) %>% 
  mutate_at(vars(selection, code), funs(str_extract(.,"[#/]([^#/]+)$"))) %>%
  mutate_at(vars(selection, code), funs(str_sub(.,2)))
```

```{r}
all_codes %>% pull(code) %>% unique

all_codes %>% filter(code == "coded_no_in_text_mentions")

all_codes %>% filter(selection == "PMC1636350_NOTREDAME-2000")
```

```{r}
all_ref_codes_query_string <- "PREFIX bioj: <http://james.howison.name/ontologies/bio-journal-sample#>
PREFIX bioj-cited: <http://james.howison.name/ontologies/bio-journal-sample-citation#>
PREFIX ca: <http://floss.syr.edu/ontologies/2008/4/contentAnalysis.owl#>
PREFIX citec: <http://james.howison.name/ontologies/software-citation-coding#> 
PREFIX dc: <http://dublincore.org/documents/2012/06/14/dcmi-terms/>
PREFIX doap: <http://usefulinc.com/ns/doap#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?reference ?code ?was_code_present ?code_label
WHERE {
  ?reference rdf:type citec:reference ;
             ca:isTargetOf [  ca:appliesCode ?ca ] .
  ?ca rdf:type ?code ;
      citec:isPresent ?was_code_present .
  OPTIONAL { ?ca rdfs:label ?code_label }
}
"
all_ref_codes_query <- data.world::qry_sparql(all_ref_codes_query_string)

all_ref_codes <- data.world::query(all_ref_codes_query, softcite_ds) %>% 
  as.tibble %>% 
  filter(str_detect(reference, "PMC")) %>% 
  mutate_at(vars(reference, code), funs(str_extract(.,"[#/]([^#/]+)$"))) %>%
  mutate_at(vars(reference, code), funs(str_sub(.,2)))
```